version: "3.3"

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./:/code
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - app